print("Time Calculator")
print("1 - Add 2 times")
print("2 - Find the difference between 2 times")
print("3 - Convert to Hours")
print("4 - Convert to Minutes")
print("5 - Convert Minutes to Time")
print("6 - Convert Hours to Time")
print("7 - Convert Days to Time")
print("8 - Exit")

user_option = int(input("Enter an option:"))